### ISSUE TITLE
PersonalizationCSP registrey key locks the lockscreen 

### ISSUE THREAD

**Issue by FredislandCocci10** [ezlage/ezAdmin#1]
Thank you for you script.

Now, with Windows 10,  using **PersonalizationCSP** registrey key locks the lockscreen background image, it is impossible for the user to modify the image. Is it possible to fix it ?

Thank you, and sorry for my english, I'm french

![image](https://github.com/user-attachments/assets/cd5392ff-1a73-4d3f-a6c6-dc6357aa93c1)

**Comment by ezlage** [comment]
Hello, @FredislandCocci10! Sorry for the delay. I've been looking into it and it's not possible to apply the images the way the script does without blocking wallpaper changes. PersonalizationCSP was the only way I found that worked for Windows Home and Pro, but if any alternatives come along, I'll be happy to consider them.
